-- Tabla para almacenar configuración de notificaciones
CREATE TABLE IF NOT EXISTS notification_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT false,
  frequency_hours INTEGER NOT NULL DEFAULT 4,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Restricción única para evitar duplicados por usuario
  UNIQUE(user_id)
);

-- Políticas de seguridad RLS (Row Level Security)
ALTER TABLE notification_settings ENABLE ROW LEVEL SECURITY;

-- Política para que los usuarios solo puedan ver sus propias configuraciones
CREATE POLICY "Users can view their own notification settings" 
  ON notification_settings 
  FOR SELECT 
  USING (auth.uid() = user_id);

-- Política para que los usuarios solo puedan insertar sus propias configuraciones
CREATE POLICY "Users can insert their own notification settings" 
  ON notification_settings 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Política para que los usuarios solo puedan actualizar sus propias configuraciones
CREATE POLICY "Users can update their own notification settings" 
  ON notification_settings 
  FOR UPDATE 
  USING (auth.uid() = user_id);

-- Índice para mejorar el rendimiento de las consultas por usuario
CREATE INDEX IF NOT EXISTS notification_settings_user_id_idx 
  ON notification_settings(user_id);
