-- Tabla para almacenar perfiles de usuario
CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Restricción única para evitar duplicados por usuario
  UNIQUE(user_id)
);

-- Políticas de seguridad RLS (Row Level Security)
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Política para que los usuarios solo puedan ver sus propios perfiles
CREATE POLICY "Users can view their own profiles" 
  ON user_profiles 
  FOR SELECT 
  USING (auth.uid() = user_id);

-- Política para que los usuarios solo puedan insertar sus propios perfiles
CREATE POLICY "Users can insert their own profiles" 
  ON user_profiles 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Política para que los usuarios solo puedan actualizar sus propios perfiles
CREATE POLICY "Users can update their own profiles" 
  ON user_profiles 
  FOR UPDATE 
  USING (auth.uid() = user_id);

-- Índice para mejorar el rendimiento de las consultas por usuario
CREATE INDEX IF NOT EXISTS user_profiles_user_id_idx 
  ON user_profiles(user_id);
